"""ajout role admin et champ suspendu

Revision ID: 00cfb39f2f1b
Revises: d9178bb22ef0
Create Date: 2026-05-20 15:37:27.857820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cfb39f2f1b'
down_revision: Union[str, Sequence[str], None] = 'd9178bb22ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('est_suspendu', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'est_suspendu')
    # ### end Alembic commands ###
