"""ajout ruelle et adresse_complete

Revision ID: 1212a48a8e89
Revises: 1d35bcd1eb49
Create Date: 2026-05-20 10:45:24.906532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1212a48a8e89'
down_revision: Union[str, Sequence[str], None] = '1d35bcd1eb49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('ruelle', sa.String(), nullable=True))
    op.add_column('annonces', sa.Column('adresse_complete', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annonces', 'adresse_complete')
    op.drop_column('annonces', 'ruelle')
    # ### end Alembic commands ###
