"""ajout equipements annonce

Revision ID: 468c3f510c6e
Revises: b10da72016e5
Create Date: 2026-05-20 07:20:58.710626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468c3f510c6e'
down_revision: Union[str, Sequence[str], None] = 'b10da72016e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('toilette_interieure', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('douche_interieure', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('cuisine_interieure', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('eau_courante', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('electricite', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('meuble', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('climatisation', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('parking', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('cloture', sa.Boolean(), nullable=True))
    op.add_column('annonces', sa.Column('gardien', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annonces', 'gardien')
    op.drop_column('annonces', 'cloture')
    op.drop_column('annonces', 'parking')
    op.drop_column('annonces', 'climatisation')
    op.drop_column('annonces', 'meuble')
    op.drop_column('annonces', 'electricite')
    op.drop_column('annonces', 'eau_courante')
    op.drop_column('annonces', 'cuisine_interieure')
    op.drop_column('annonces', 'douche_interieure')
    op.drop_column('annonces', 'toilette_interieure')
    # ### end Alembic commands ###
