"""creation tables initiales

Revision ID: b10da72016e5
Revises: 
Create Date: 2026-05-20 07:01:27.200873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10da72016e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('mot_de_passe', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('proprietaire', 'locataire', name='userrole'), nullable=False),
    sa.Column('est_verifie', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('annonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('ville', sa.String(), nullable=False),
    sa.Column('quartier', sa.String(), nullable=True),
    sa.Column('type_logement', sa.String(), nullable=False),
    sa.Column('nb_chambres', sa.Integer(), nullable=False),
    sa.Column('est_disponible', sa.Boolean(), nullable=True),
    sa.Column('est_verifie', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('proprietaire_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annonces_id'), 'annonces', ['id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('annonce_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['annonce_id'], ['annonces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_annonces_id'), table_name='annonces')
    op.drop_table('annonces')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
