"""ajout tokens verification et reset password

Revision ID: d9178bb22ef0
Revises: 1212a48a8e89
Create Date: 2026-05-20 15:13:02.157650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9178bb22ef0'
down_revision: Union[str, Sequence[str], None] = '1212a48a8e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_verification', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_reset_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('token_reset_expire', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_reset_expire')
    op.drop_column('users', 'token_reset_password')
    op.drop_column('users', 'token_verification')
    # ### end Alembic commands ###
